
- 1. Birth Rate: Number of births per 1,000 population per year.
- 2. health: Total health spending as %age of Total GDP
- 3. Hepatitis_B: Represents % of coverage of Hepatitis B (HepB3) immunization among 1-year-olds.
- 4. Measles: Represents % of coverage of Measles containing vaccine first dose (MCV1) immunization among 1-year-olds
- 5. income: Net income per person
- 6. inflation: The measurement of the annual growth rate of the Total GDP
- 7. Alcohol_consumption: Represents alcohol consumption that is recorded in liters of pure alcohol per capita with 15+ years old
- 8. BMI: BMI is a measure of nutritional status in adults. It is defined as a person's weight in kilograms divided by the square of
- 9. Polio: Represents % of coverage of Polio (Pol3) immunization among 1-year-olds.
- 10. Diphtheria: Represents % of coverage of Diphtheria tetanus toxoid and pertussis (DTP3) immunization among 1-year-olds.
- 11. Incidents_HIV
- 12. Schooling: Average years that people aged 25+ spent in formal education
- 13. GDP: Gross Domestic Product, the total value of goods and services produced in the country.
- 14. Gross tertiary education enrollment (%): Gross enrollment ratio for tertiary education.
- 15. Infant mortality: Number of deaths per 1,000 live births before reaching one year of age.
- 16. Life expectancy: Average number of years a newborn is expected to live.
- 17. Maternal mortality ratio: Number of maternal deaths per 100,000 live births.
- 18. Physicians per thousand: Number of physicians per thousand people.
- 19. Unemployment rate: Percentage of the labor force that is unemployed.
- 20. Urban_population: Percentage of the population living in urban areas.
- 21. Clean fuel %: Percentage of the population with access to clean fuel for making food
- 22. GDP per capita: GDP/population
- 23. country
- 24. region
- 25. population: number of citizens


principle faktors:
1. technology
2. education
3. disposable income
4. urbanization
5. inequality
6. healthcare
7. health risks/epidemics

In [57]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [58]:
# if you want to change the format, for example to avoid scientific notation, e.g. e+04
pd.set_option('display.float_format', lambda x: '%.1f' % x)

In [59]:
# Supress Warnings
import warnings
warnings.filterwarnings('ignore')

# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# visulaisation
from matplotlib.pyplot import xticks
%matplotlib inline

# Data display coustomization
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 50)

In [60]:
d1 = pd.read_csv("/Users/cej12/Skrivebord/data/Country-data.csv")
d1

,country,child_mort,exports,health,imports,income,inflation,life_expec,total_fer,gdpp
0,Afghanistan,90.2,10.0,7.6,44.9,1610,9.4,56.2,5.8,553
1,Albania,16.6,28.0,6.5,48.6,9930,4.5,76.3,1.6,4090
2,Algeria,27.3,38.4,4.2,31.4,12900,16.1,76.5,2.9,4460
3,Angola,119.0,62.3,2.9,42.9,5900,22.4,60.1,6.2,3530
4,Antigua and Barbuda,10.3,45.5,6.0,58.9,19100,1.4,76.8,2.1,12200
...,...,...,...,...,...,...,...,...,...,...
162,Vanuatu,29.2,46.6,5.2,52.7,2950,2.6,63.0,3.5,2970
163,Venezuela,17.1,28.5,4.9,17.6,16500,45.9,75.4,2.5,13500
164,Vietnam,23.3,72.0,6.8,80.2,4490,12.1,73.1,1.9,1310
165,Yemen,56.3,30.0,5.2,34.4,4480,23.6,67.5,4.7,1310
166,Zambia,83.1,37.0,5.9,30.9,3280,14.0,52.0,5.4,1460

In [61]:
d1 = d1.drop('gdpp', axis = 1)
d1 = d1.drop('child_mort', axis = 1)
d1 = d1.drop('imports', axis = 1)
d1 = d1.drop('exports', axis = 1)
d1 = d1.drop('total_fer', axis = 1)
d1 = d1.drop('life_expec', axis = 1)
d1

                 country  health  income  inflation
0            Afghanistan     7.6    1610        9.4
1                Albania     6.5    9930        4.5
2                Algeria     4.2   12900       16.1
3                 Angola     2.9    5900       22.4
4    Antigua and Barbuda     6.0   19100        1.4
..                   ...     ...     ...        ...
162              Vanuatu     5.2    2950        2.6
163            Venezuela     4.9   16500       45.9
164              Vietnam     6.8    4490       12.1
165                Yemen     5.2    4480       23.6
166               Zambia     5.9    3280       14.0

[167 rows x 4 columns]

In [62]:
d2 = pd.read_csv("/Users/cej12/Skrivebord/data/Life-Expectancy-Data-Updated.csv")
d2

,Country,Region,Year,Infant_deaths,Under_five_deaths,Adult_mortality,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,GDP_per_capita,Population_mln,Thinness_ten_nineteen_years,Thinness_five_nine_years,Schooling,Economy_status_Developed,Economy_status_Developing,Life_expectancy
0,Turkiye,Middle East,2015,11.1,13.0,105.8,1.3,97,65,27.8,97,97,0.1,11006,78.5,4.9,4.8,7.8,0,1,76.5
1,Spain,European Union,2015,2.7,3.3,57.9,10.3,97,94,26.0,97,97,0.1,25742,46.4,0.6,0.5,9.7,1,0,82.8
2,India,Asia,2007,51.5,67.9,201.1,1.6,60,35,21.2,67,64,0.1,1076,1183.2,27.1,28.0,5.0,0,1,65.4
3,Guyana,South America,2006,32.8,40.5,222.2,5.7,93,74,25.3,92,93,0.8,4146,0.8,5.7,5.5,7.9,0,1,67.0
4,Israel,Middle East,2012,3.4,4.3,58.0,2.9,97,89,27.0,94,94,0.1,33995,7.9,1.2,1.1,12.8,1,0,81.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2859,Niger,Africa,2000,97.0,224.9,291.8,0.1,72,64,20.8,41,34,0.5,399,11.3,12.8,12.9,1.1,0,1,49.9
2860,Mongolia,Asia,2009,23.9,28.6,235.2,6.6,97,97,25.3,96,95,0.0,2515,2.7,2.2,2.3,9.1,0,1,66.9
2861,Sri Lanka,Asia,2004,17.7,28.9,134.9,1.6,62,95,21.9,97,97,0.0,2130,19.4,15.4,15.5,10.3,0,1,74.3
2862,Lithuania,European Union,2002,7.9,9.9,204.0,11.0,94,95,26.1,97,95,0.1,7424,3.4,3.3,3.3,11.1,1,0,71.8
2863,Iceland,Rest of Europe,2011,2.1,2.6,50.6,6.8,88,90,26.1,95,95,0.1,48934,0.3,0.9,0.9,11.0,1,0,82.4

In [63]:
# Creating one column out of developing and developed economy status
d2['Status'] = d2['Economy_status_Developed']
d2.drop(['Economy_status_Developed', 'Economy_status_Developing'], axis=1, inplace=True)

In [64]:
#d2 = d2.drop('Year', axis = 1)
d2 = d2.drop('GDP_per_capita', axis = 1)
d2 = d2.drop('Population_mln', axis = 1)
d2 = d2.drop('Thinness_ten_nineteen_years', axis = 1)
d2 = d2.drop('Thinness_five_nine_years', axis = 1)
#d2 = d2.drop('Economy_status_Developed', axis = 1)
#d2 = d2.drop('Economy_status_Developing', axis = 1)
d2 = d2.drop('Life_expectancy', axis = 1)
d2 = d2.drop('Infant_deaths', axis = 1)
d2 = d2.drop('Under_five_deaths', axis = 1)
d2 = d2.drop('Adult_mortality', axis = 1)

d2

,Country,Region,Year,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,Schooling,Status
0,Turkiye,Middle East,2015,1.3,97,65,27.8,97,97,0.1,7.8,0
1,Spain,European Union,2015,10.3,97,94,26.0,97,97,0.1,9.7,1
2,India,Asia,2007,1.6,60,35,21.2,67,64,0.1,5.0,0
3,Guyana,South America,2006,5.7,93,74,25.3,92,93,0.8,7.9,0
4,Israel,Middle East,2012,2.9,97,89,27.0,94,94,0.1,12.8,1
...,...,...,...,...,...,...,...,...,...,...,...,...
2859,Niger,Africa,2000,0.1,72,64,20.8,41,34,0.5,1.1,0
2860,Mongolia,Asia,2009,6.6,97,97,25.3,96,95,0.0,9.1,0
2861,Sri Lanka,Asia,2004,1.6,62,95,21.9,97,97,0.0,10.3,0
2862,Lithuania,European Union,2002,11.0,94,95,26.1,97,95,0.1,11.1,1
2863,Iceland,Rest of Europe,2011,6.8,88,90,26.1,95,95,0.1,11.0,1

In [65]:
d2_2015 = d2[d2.Year == 2015]
d2_2015 = d2_2015.drop('Year', axis = 1)
d2_2015

,Country,Region,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,Schooling,Status
0,Turkiye,Middle East,1.3,97,65,27.8,97,97,0.1,7.8,0
1,Spain,European Union,10.3,97,94,26.0,97,97,0.1,9.7,1
6,Russian Federation,Rest of Europe,8.1,97,97,26.2,97,97,0.1,12.0,0
27,Cameroon,Africa,4.5,84,64,24.3,77,84,1.1,6.1,0
43,"Gambia, The",Africa,2.7,97,64,23.9,96,97,1.0,3.4,0
...,...,...,...,...,...,...,...,...,...,...,...
2753,Tunisia,Africa,1.5,98,98,26.3,98,98,0.0,7.0,0
2820,"Venezuela, RB",South America,6.2,87,83,26.7,87,87,0.4,10.1,0
2840,Djibouti,Africa,0.3,84,82,24.0,84,84,0.2,4.1,0
2846,Nicaragua,Central America and Caribbean,3.7,98,83,27.2,99,98,0.1,6.5,0
2848,Bahrain,Middle East,1.5,98,99,24.8,98,98,0.1,9.3,0

In [66]:
d2_2015.at[6,'Country']='Russia'
d2_2015.at[0,'Country']='Turkey'
d2_2015.at[43,'Country']='The Gambia'
d2_2015.at[2820,'Country']='Venezuela'

In [67]:
d2_2015

,Country,Region,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,Schooling,Status
0,Turkey,Middle East,1.3,97,65,27.8,97,97,0.1,7.8,0
1,Spain,European Union,10.3,97,94,26.0,97,97,0.1,9.7,1
6,Russia,Rest of Europe,8.1,97,97,26.2,97,97,0.1,12.0,0
27,Cameroon,Africa,4.5,84,64,24.3,77,84,1.1,6.1,0
43,The Gambia,Africa,2.7,97,64,23.9,96,97,1.0,3.4,0
...,...,...,...,...,...,...,...,...,...,...,...
2753,Tunisia,Africa,1.5,98,98,26.3,98,98,0.0,7.0,0
2820,Venezuela,South America,6.2,87,83,26.7,87,87,0.4,10.1,0
2840,Djibouti,Africa,0.3,84,82,24.0,84,84,0.2,4.1,0
2846,Nicaragua,Central America and Caribbean,3.7,98,83,27.2,99,98,0.1,6.5,0
2848,Bahrain,Middle East,1.5,98,99,24.8,98,98,0.1,9.3,0

In [68]:
d3 = pd.read_csv("/Users/cej12/Skrivebord/data/world-data-2023.csv")
d3

,Country,Density\n(P/Km2),Abbreviation,Agricultural Land( %),Land Area(Km2),Armed Forces size,Birth Rate,Calling Code,Capital/Major City,Co2-Emissions,CPI,CPI Change (%),Currency-Code,Fertility Rate,Forested Area (%),Gasoline Price,GDP,Gross primary education enrollment (%),Gross tertiary education enrollment (%),Infant mortality,Largest city,Life expectancy,Maternal mortality ratio,Minimum wage,Official language,Out of pocket health expenditure,Physicians per thousand,Population,Population: Labor force participation (%),Tax revenue (%),Total tax rate,Unemployment rate,Urban_population,Latitude,Longitude
0,Afghanistan,60,AF,58.10%,"652,230","323,000",32.5,93.0,Kabul,"8,672",149.9,2.30%,AFN,4.5,2.10%,$0.70,"$19,101,353,833",104.00%,9.70%,47.9,Kabul,64.5,638.0,$0.43,Pashto,78.40%,0.3,"38,041,754",48.90%,9.30%,71.40%,11.12%,"9,797,273",33.9,67.7
1,Albania,105,AL,43.10%,"28,748","9,000",11.8,355.0,Tirana,"4,536",119.05,1.40%,ALL,1.6,28.10%,$1.36,"$15,278,077,447",107.00%,55.00%,7.8,Tirana,78.5,15.0,$1.12,Albanian,56.90%,1.2,"2,854,191",55.70%,18.60%,36.60%,12.33%,"1,747,593",41.2,20.2
2,Algeria,18,DZ,17.40%,"2,381,741","317,000",24.3,213.0,Algiers,"150,006",151.36,2.00%,DZD,3.0,0.80%,$0.28,"$169,988,236,398",109.90%,51.40%,20.1,Algiers,76.7,112.0,$0.95,Arabic,28.10%,1.7,"43,053,054",41.20%,37.20%,66.10%,11.70%,"31,510,100",28.0,1.7
3,Andorra,164,AD,40.00%,468,NaN,7.2,376.0,Andorra la Vella,469,NaN,NaN,EUR,1.3,34.00%,$1.51,"$3,154,057,987",106.40%,NaN,2.7,Andorra la Vella,NaN,NaN,$6.63,Catalan,36.40%,3.3,"77,142",NaN,NaN,NaN,NaN,"67,873",42.5,1.5
4,Angola,26,AO,47.50%,"1,246,700","117,000",40.7,244.0,Luanda,"34,693",261.73,17.10%,AOA,5.5,46.30%,$0.97,"$94,635,415,870",113.50%,9.30%,51.6,Luanda,60.8,241.0,$0.71,Portuguese,33.40%,0.2,"31,825,295",77.50%,9.20%,49.10%,6.89%,"21,061,025",-11.2,17.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,32,VE,24.50%,"912,050","343,000",17.9,58.0,Caracas,"164,175","2,740.27",254.90%,VED,2.3,52.70%,$0.00,"$482,359,318,768",97.20%,79.30%,21.4,Caracas,72.1,125.0,$0.01,Spanish,45.80%,1.9,"28,515,829",59.70%,NaN,73.30%,8.80%,"25,162,368",6.4,-66.6
191,Vietnam,314,VN,39.30%,"331,210","522,000",16.8,84.0,Hanoi,"192,668",163.52,2.80%,VND,2.0,48.10%,$0.80,"$261,921,244,843",110.60%,28.50%,16.5,Ho Chi Minh City,75.3,43.0,$0.73,Vietnamese,43.50%,0.8,"96,462,106",77.40%,19.10%,37.60%,2.01%,"35,332,140",14.1,108.3
192,Yemen,56,YE,44.60%,"527,968","40,000",30.4,967.0,Sanaa,"10,609",157.58,8.10%,YER,3.8,1.00%,$0.92,"$26,914,402,224",93.60%,10.20%,42.9,Sanaa,66.1,164.0,NaN,Arabic,81.00%,0.3,"29,161,922",38.00%,NaN,26.60%,12.91%,"10,869,523",15.6,48.5
193,Zambia,25,ZM,32.10%,"752,618","16,000",36.2,260.0,Lusaka,"5,141",212.31,9.20%,ZMW,4.6,65.20%,$1.40,"$23,064,722,446",98.70%,4.10%,40.4,Lusaka,63.5,213.0,$0.24,English,27.50%,1.2,"17,861,030",74.60%,16.20%,15.60%,11.43%,"7,871,713",-13.1,27.8
194,Zimbabwe,38,ZW,41.90%,"390,757","51,000",30.7,263.0,Harare,"10,983",105.51,0.90%,NaN,3.6,35.50%,$1.34,"$21,440,758,800",109.90%,10.00%,33.9,Harare,61.2,458.0,NaN,Shona,25.80%,0.2,"14,645,468",83.10%,20.70%,31.60%,4.95%,"4,717,305",-19.0,29.2

In [69]:
d3 = d3.drop('Abbreviation', axis = 1)
d3 = d3.drop('Agricultural Land( %)', axis = 1)
d3 = d3.drop('Armed Forces size', axis = 1)
d3 = d3.drop('Calling Code', axis = 1)
d3 = d3.drop('Capital/Major City', axis = 1)
d3 = d3.drop('Co2-Emissions', axis = 1)
d3 = d3.drop('Forested Area (%)', axis = 1)
d3 = d3.drop('Currency-Code', axis = 1)
d3 = d3.drop('Gasoline Price', axis = 1)
d3 = d3.drop('Largest city', axis = 1)
d3 = d3.drop('Minimum wage', axis = 1)
d3 = d3.drop('Official language', axis = 1)
d3 = d3.drop('Out of pocket health expenditure', axis = 1)
d3 = d3.drop('Tax revenue (%)', axis = 1)
d3 = d3.drop('Total tax rate', axis = 1)
d3 = d3.drop('Latitude', axis = 1)
d3 = d3.drop('Longitude', axis = 1)
d3 = d3.drop('Land Area(Km2)', axis = 1)
d3 = d3.drop('Density\n(P/Km2)', axis = 1)
d3 = d3.drop('Population: Labor force participation (%)', axis = 1)
d3 = d3.drop('CPI', axis = 1)
d3 = d3.drop('CPI Change (%)', axis = 1)
d3 = d3.drop('Fertility Rate', axis = 1)
d3 = d3.drop('Gross primary education enrollment (%)', axis = 1)
d3

,Country,Birth Rate,GDP,Gross tertiary education enrollment (%),Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Population,Unemployment rate,Urban_population
0,Afghanistan,32.5,"$19,101,353,833",9.70%,47.9,64.5,638.0,0.3,"38,041,754",11.12%,"9,797,273"
1,Albania,11.8,"$15,278,077,447",55.00%,7.8,78.5,15.0,1.2,"2,854,191",12.33%,"1,747,593"
2,Algeria,24.3,"$169,988,236,398",51.40%,20.1,76.7,112.0,1.7,"43,053,054",11.70%,"31,510,100"
3,Andorra,7.2,"$3,154,057,987",NaN,2.7,NaN,NaN,3.3,"77,142",NaN,"67,873"
4,Angola,40.7,"$94,635,415,870",9.30%,51.6,60.8,241.0,0.2,"31,825,295",6.89%,"21,061,025"
...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,17.9,"$482,359,318,768",79.30%,21.4,72.1,125.0,1.9,"28,515,829",8.80%,"25,162,368"
191,Vietnam,16.8,"$261,921,244,843",28.50%,16.5,75.3,43.0,0.8,"96,462,106",2.01%,"35,332,140"
192,Yemen,30.4,"$26,914,402,224",10.20%,42.9,66.1,164.0,0.3,"29,161,922",12.91%,"10,869,523"
193,Zambia,36.2,"$23,064,722,446",4.10%,40.4,63.5,213.0,1.2,"17,861,030",11.43%,"7,871,713"
194,Zimbabwe,30.7,"$21,440,758,800",10.00%,33.9,61.2,458.0,0.2,"14,645,468",4.95%,"4,717,305"

In [70]:
d3.columns

Index(['Country', 'Birth Rate', 'GDP',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Life expectancy', 'Maternal mortality ratio',
       'Physicians per thousand', 'Population', 'Unemployment rate',
       'Urban_population'],
      dtype='object')

In [71]:
columns_to_convert = ['Birth Rate', 'GDP',
       'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Life expectancy', 'Maternal mortality ratio',
       'Physicians per thousand', 'Population', 'Unemployment rate',
       'Urban_population']

In [72]:
# Convert columns using a lambda function
d3[columns_to_convert] = d3[columns_to_convert].applymap(lambda x: float(str(x).replace(',', '').replace('$', '').replace('%', '')))
d3

,Country,Birth Rate,GDP,Gross tertiary education enrollment (%),Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Population,Unemployment rate,Urban_population
0,Afghanistan,32.5,19101353833.0,9.7,47.9,64.5,638.0,0.3,38041754.0,11.1,9797273.0
1,Albania,11.8,15278077447.0,55.0,7.8,78.5,15.0,1.2,2854191.0,12.3,1747593.0
2,Algeria,24.3,169988236398.0,51.4,20.1,76.7,112.0,1.7,43053054.0,11.7,31510100.0
3,Andorra,7.2,3154057987.0,NaN,2.7,NaN,NaN,3.3,77142.0,NaN,67873.0
4,Angola,40.7,94635415870.0,9.3,51.6,60.8,241.0,0.2,31825295.0,6.9,21061025.0
...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,17.9,482359318768.0,79.3,21.4,72.1,125.0,1.9,28515829.0,8.8,25162368.0
191,Vietnam,16.8,261921244843.0,28.5,16.5,75.3,43.0,0.8,96462106.0,2.0,35332140.0
192,Yemen,30.4,26914402224.0,10.2,42.9,66.1,164.0,0.3,29161922.0,12.9,10869523.0
193,Zambia,36.2,23064722446.0,4.1,40.4,63.5,213.0,1.2,17861030.0,11.4,7871713.0
194,Zimbabwe,30.7,21440758800.0,10.0,33.9,61.2,458.0,0.2,14645468.0,5.0,4717305.0

In [73]:
d3.isnull().sum()

Country                                     0
Birth Rate                                  6
GDP                                         2
Gross tertiary education enrollment (%)    12
Infant mortality                            6
Life expectancy                             8
Maternal mortality ratio                   14
Physicians per thousand                     7
Population                                  1
Unemployment rate                          19
Urban_population                            5
dtype: int64

In [74]:
# List of columns with missing values
columns_with_missing = d3.columns[d3.isnull().any()]
columns_with_missing

Index(['Birth Rate', 'GDP', 'Gross tertiary education enrollment (%)',
       'Infant mortality', 'Life expectancy', 'Maternal mortality ratio',
       'Physicians per thousand', 'Population', 'Unemployment rate',
       'Urban_population'],
      dtype='object')

In [75]:
# Impute numerical columns with mean
numerical_columns = d3.select_dtypes(include=['float64'])
numerical_columns = numerical_columns.columns[numerical_columns.isnull().any()]
d3[numerical_columns] = d3[numerical_columns].fillna(d3[numerical_columns].mean())

In [76]:
# Impute categorical columns with mode
#categorical_columns = d3.select_dtypes(include=['object'])
#categorical_columns = categorical_columns.columns[categorical_columns.isnull().any()]
#d3[categorical_columns] = d3[categorical_columns].fillna(d3[categorical_columns].mode().iloc[0])

In [77]:
missing_counts = d3.isnull().sum()
print(missing_counts)

Country                                    0
Birth Rate                                 0
GDP                                        0
Gross tertiary education enrollment (%)    0
Infant mortality                           0
Life expectancy                            0
Maternal mortality ratio                   0
Physicians per thousand                    0
Population                                 0
Unemployment rate                          0
Urban_population                           0
dtype: int64

In [78]:
# read the Excel file from your data folder into a data frame
data4 = pd.read_csv("/Users/cej12/Skrivebord/data/fuel.csv")
data4

,Series Name,Series Code,Country Name,Country Code,2021 [YR2021]
0,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,Afghanistan,AFG,35.4
1,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,Albania,ALB,83.7
2,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,Algeria,DZA,99.7
3,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,American Samoa,ASM,..
4,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,Andorra,AND,100
...,...,...,...,...,...
207,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,Venezuela,VEN,95.5
208,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,Vietnam,VNM,96.1
209,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,Yemen,YEM,61.3
210,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,Zambia,ZMB,10.2
211,Access to clean fuels and technologies for coo...,EG.CFT.ACCS.ZS,Zimbabwe,ZWE,30.3

In [79]:
data4.at[158,'Country Name']='Russia'
data4.at[195,'Country Name']='Turkey'

In [80]:
data4 = data4.drop('Series Name', axis = 1)
data4 = data4.drop('Series Code', axis = 1)
data4 = data4.drop('Country Code', axis = 1)
data4.rename(columns={'2021 [YR2021]': 'Clean fuel %'},
inplace=True)

In [81]:
data4.isnull().sum()

Country Name    0
Clean fuel %    0
dtype: int64

In [82]:
(data4 == 0).sum()

Country Name    0
Clean fuel %    0
dtype: int64

In [83]:
data4

       Country Name Clean fuel %
0       Afghanistan         35.4
1           Albania         83.7
2           Algeria         99.7
3    American Samoa           ..
4           Andorra          100
..              ...          ...
207       Venezuela         95.5
208         Vietnam         96.1
209           Yemen         61.3
210          Zambia         10.2
211        Zimbabwe         30.3

[212 rows x 2 columns]

In [84]:
d1

                 country  health  income  inflation
0            Afghanistan     7.6    1610        9.4
1                Albania     6.5    9930        4.5
2                Algeria     4.2   12900       16.1
3                 Angola     2.9    5900       22.4
4    Antigua and Barbuda     6.0   19100        1.4
..                   ...     ...     ...        ...
162              Vanuatu     5.2    2950        2.6
163            Venezuela     4.9   16500       45.9
164              Vietnam     6.8    4490       12.1
165                Yemen     5.2    4480       23.6
166               Zambia     5.9    3280       14.0

[167 rows x 4 columns]

In [85]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   country    167 non-null    object
 1   health     167 non-null    float64
 2   income     167 non-null    int64
 3   inflation  167 non-null    float64
dtypes: float64(2), int64(1), object(1)
memory usage: 5.3+ KB

In [86]:
#sort A to Z
cd2 = d2_2015.sort_values('Country')
cd2

,Country,Region,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,Schooling,Status
1066,Afghanistan,Asia,0.0,65,42,23.3,67,65,0.0,3.6,0
626,Albania,Rest of Europe,4.3,99,98,26.6,99,99,0.0,9.7,0
57,Algeria,Africa,0.6,95,99,25.5,95,95,0.1,7.9,0
216,Angola,Africa,6.5,64,64,23.2,62,64,0.9,5.0,0
696,Antigua and Barbuda,Central America and Caribbean,9.1,99,84,26.6,86,99,0.2,9.2,0
...,...,...,...,...,...,...,...,...,...,...,...
2820,Venezuela,South America,6.2,87,83,26.7,87,87,0.4,10.1,0
112,Vietnam,Asia,3.0,97,65,21.7,97,97,0.1,8.0,0
1706,"Yemen, Rep.",Middle East,0.0,69,95,23.7,63,69,0.0,3.0,0
1709,Zambia,Africa,3.5,90,47,22.5,90,90,4.5,6.9,0
1480,Zimbabwe,Africa,3.8,87,64,23.8,88,87,3.9,8.2,0

In [87]:
d2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2864 entries, 0 to 2863
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Country              2864 non-null   object
 1   Region               2864 non-null   object
 2   Year                 2864 non-null   int64
 3   Alcohol_consumption  2864 non-null   float64
 4   Hepatitis_B          2864 non-null   int64
 5   Measles              2864 non-null   int64
 6   BMI                  2864 non-null   float64
 7   Polio                2864 non-null   int64
 8   Diphtheria           2864 non-null   int64
 9   Incidents_HIV        2864 non-null   float64
 10  Schooling            2864 non-null   float64
 11  Status               2864 non-null   int64
dtypes: float64(4), int64(6), object(2)
memory usage: 268.6+ KB

In [88]:
d3

,Country,Birth Rate,GDP,Gross tertiary education enrollment (%),Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Population,Unemployment rate,Urban_population
0,Afghanistan,32.5,19101353833.0,9.7,47.9,64.5,638.0,0.3,38041754.0,11.1,9797273.0
1,Albania,11.8,15278077447.0,55.0,7.8,78.5,15.0,1.2,2854191.0,12.3,1747593.0
2,Algeria,24.3,169988236398.0,51.4,20.1,76.7,112.0,1.7,43053054.0,11.7,31510100.0
3,Andorra,7.2,3154057987.0,38.0,2.7,72.3,160.4,3.3,77142.0,6.9,67873.0
4,Angola,40.7,94635415870.0,9.3,51.6,60.8,241.0,0.2,31825295.0,6.9,21061025.0
...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,17.9,482359318768.0,79.3,21.4,72.1,125.0,1.9,28515829.0,8.8,25162368.0
191,Vietnam,16.8,261921244843.0,28.5,16.5,75.3,43.0,0.8,96462106.0,2.0,35332140.0
192,Yemen,30.4,26914402224.0,10.2,42.9,66.1,164.0,0.3,29161922.0,12.9,10869523.0
193,Zambia,36.2,23064722446.0,4.1,40.4,63.5,213.0,1.2,17861030.0,11.4,7871713.0
194,Zimbabwe,30.7,21440758800.0,10.0,33.9,61.2,458.0,0.2,14645468.0,5.0,4717305.0

In [89]:
d3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 195 entries, 0 to 194
Data columns (total 11 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Country                                  195 non-null    object
 1   Birth Rate                               195 non-null    float64
 2   GDP                                      195 non-null    float64
 3   Gross tertiary education enrollment (%)  195 non-null    float64
 4   Infant mortality                         195 non-null    float64
 5   Life expectancy                          195 non-null    float64
 6   Maternal mortality ratio                 195 non-null    float64
 7   Physicians per thousand                  195 non-null    float64
 8   Population                               195 non-null    float64
 9   Unemployment rate                        195 non-null    float64
 10  Urban_population                         195 non-null    float64
dtypes: float64(10), object(1)
memory usage: 16.9+ KB

In [90]:
data4

       Country Name Clean fuel %
0       Afghanistan         35.4
1           Albania         83.7
2           Algeria         99.7
3    American Samoa           ..
4           Andorra          100
..              ...          ...
207       Venezuela         95.5
208         Vietnam         96.1
209           Yemen         61.3
210          Zambia         10.2
211        Zimbabwe         30.3

[212 rows x 2 columns]

In [91]:
data4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Country Name  212 non-null    object
 1   Clean fuel %  212 non-null    object
dtypes: object(2)
memory usage: 3.4+ KB

In [92]:
cd1 = d1.copy()
cd1

                 country  health  income  inflation
0            Afghanistan     7.6    1610        9.4
1                Albania     6.5    9930        4.5
2                Algeria     4.2   12900       16.1
3                 Angola     2.9    5900       22.4
4    Antigua and Barbuda     6.0   19100        1.4
..                   ...     ...     ...        ...
162              Vanuatu     5.2    2950        2.6
163            Venezuela     4.9   16500       45.9
164              Vietnam     6.8    4490       12.1
165                Yemen     5.2    4480       23.6
166               Zambia     5.9    3280       14.0

[167 rows x 4 columns]

In [93]:
cd2

,Country,Region,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,Schooling,Status
1066,Afghanistan,Asia,0.0,65,42,23.3,67,65,0.0,3.6,0
626,Albania,Rest of Europe,4.3,99,98,26.6,99,99,0.0,9.7,0
57,Algeria,Africa,0.6,95,99,25.5,95,95,0.1,7.9,0
216,Angola,Africa,6.5,64,64,23.2,62,64,0.9,5.0,0
696,Antigua and Barbuda,Central America and Caribbean,9.1,99,84,26.6,86,99,0.2,9.2,0
...,...,...,...,...,...,...,...,...,...,...,...
2820,Venezuela,South America,6.2,87,83,26.7,87,87,0.4,10.1,0
112,Vietnam,Asia,3.0,97,65,21.7,97,97,0.1,8.0,0
1706,"Yemen, Rep.",Middle East,0.0,69,95,23.7,63,69,0.0,3.0,0
1709,Zambia,Africa,3.5,90,47,22.5,90,90,4.5,6.9,0
1480,Zimbabwe,Africa,3.8,87,64,23.8,88,87,3.9,8.2,0

In [94]:
cd3 = d3.copy()
cd3

,Country,Birth Rate,GDP,Gross tertiary education enrollment (%),Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Population,Unemployment rate,Urban_population
0,Afghanistan,32.5,19101353833.0,9.7,47.9,64.5,638.0,0.3,38041754.0,11.1,9797273.0
1,Albania,11.8,15278077447.0,55.0,7.8,78.5,15.0,1.2,2854191.0,12.3,1747593.0
2,Algeria,24.3,169988236398.0,51.4,20.1,76.7,112.0,1.7,43053054.0,11.7,31510100.0
3,Andorra,7.2,3154057987.0,38.0,2.7,72.3,160.4,3.3,77142.0,6.9,67873.0
4,Angola,40.7,94635415870.0,9.3,51.6,60.8,241.0,0.2,31825295.0,6.9,21061025.0
...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,17.9,482359318768.0,79.3,21.4,72.1,125.0,1.9,28515829.0,8.8,25162368.0
191,Vietnam,16.8,261921244843.0,28.5,16.5,75.3,43.0,0.8,96462106.0,2.0,35332140.0
192,Yemen,30.4,26914402224.0,10.2,42.9,66.1,164.0,0.3,29161922.0,12.9,10869523.0
193,Zambia,36.2,23064722446.0,4.1,40.4,63.5,213.0,1.2,17861030.0,11.4,7871713.0
194,Zimbabwe,30.7,21440758800.0,10.0,33.9,61.2,458.0,0.2,14645468.0,5.0,4717305.0

In [95]:
cd4 = data4.copy()
cd4

       Country Name Clean fuel %
0       Afghanistan         35.4
1           Albania         83.7
2           Algeria         99.7
3    American Samoa           ..
4           Andorra          100
..              ...          ...
207       Venezuela         95.5
208         Vietnam         96.1
209           Yemen         61.3
210          Zambia         10.2
211        Zimbabwe         30.3

[212 rows x 2 columns]

In [96]:
cd1.isnull().sum()

country      0
health       0
income       0
inflation    0
dtype: int64

In [97]:
(cd1 == 0).sum()

country      0
health       0
income       0
inflation    0
dtype: int64

In [98]:
cd2.isnull().sum()

Country                0
Region                 0
Alcohol_consumption    0
Hepatitis_B            0
Measles                0
BMI                    0
Polio                  0
Diphtheria             0
Incidents_HIV          0
Schooling              0
Status                 0
dtype: int64

In [99]:
(cd2 == 0).sum()

Country                  0
Region                   0
Alcohol_consumption      5
Hepatitis_B              0
Measles                  0
BMI                      0
Polio                    0
Diphtheria               0
Incidents_HIV            0
Schooling                0
Status                 142
dtype: int64

In [100]:
cd3.isnull().sum()

Country                                    0
Birth Rate                                 0
GDP                                        0
Gross tertiary education enrollment (%)    0
Infant mortality                           0
Life expectancy                            0
Maternal mortality ratio                   0
Physicians per thousand                    0
Population                                 0
Unemployment rate                          0
Urban_population                           0
dtype: int64

In [101]:
(cd3 == 0).sum()

Country                                    0
Birth Rate                                 0
GDP                                        0
Gross tertiary education enrollment (%)    0
Infant mortality                           0
Life expectancy                            0
Maternal mortality ratio                   0
Physicians per thousand                    0
Population                                 0
Unemployment rate                          0
Urban_population                           0
dtype: int64

In [102]:
cd4.isnull().sum()

Country Name    0
Clean fuel %    0
dtype: int64

In [103]:
(cd4 == 0).sum()

Country Name    0
Clean fuel %    0
dtype: int64

In [104]:
missing_counts = cd3.isnull().sum()
print(missing_counts)

Country                                    0
Birth Rate                                 0
GDP                                        0
Gross tertiary education enrollment (%)    0
Infant mortality                           0
Life expectancy                            0
Maternal mortality ratio                   0
Physicians per thousand                    0
Population                                 0
Unemployment rate                          0
Urban_population                           0
dtype: int64

In [105]:
test1 = cd2[cd2.Alcohol_consumption == 0]
test1

,Country,Region,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,Schooling,Status
1066,Afghanistan,Asia,0.0,65,42,23.3,67,65,0.0,3.6,0
590,Kuwait,Middle East,0.0,99,96,29.5,99,99,0.1,7.1,0
1628,Mauritania,Africa,0.0,73,64,24.9,67,73,0.1,4.3,0
638,Saudi Arabia,Middle East,0.0,98,96,28.4,97,98,0.1,9.5,0
1874,Somalia,Africa,0.0,42,64,23.1,47,42,0.1,2.1,0

In [106]:
cd1.rename(columns={'country': 'Country'},inplace=True)
cd4.rename(columns={'Country Name': 'Country'},inplace=True)

In [107]:
cd1

                 Country  health  income  inflation
0            Afghanistan     7.6    1610        9.4
1                Albania     6.5    9930        4.5
2                Algeria     4.2   12900       16.1
3                 Angola     2.9    5900       22.4
4    Antigua and Barbuda     6.0   19100        1.4
..                   ...     ...     ...        ...
162              Vanuatu     5.2    2950        2.6
163            Venezuela     4.9   16500       45.9
164              Vietnam     6.8    4490       12.1
165                Yemen     5.2    4480       23.6
166               Zambia     5.9    3280       14.0

[167 rows x 4 columns]

In [108]:
cd2

,Country,Region,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,Schooling,Status
1066,Afghanistan,Asia,0.0,65,42,23.3,67,65,0.0,3.6,0
626,Albania,Rest of Europe,4.3,99,98,26.6,99,99,0.0,9.7,0
57,Algeria,Africa,0.6,95,99,25.5,95,95,0.1,7.9,0
216,Angola,Africa,6.5,64,64,23.2,62,64,0.9,5.0,0
696,Antigua and Barbuda,Central America and Caribbean,9.1,99,84,26.6,86,99,0.2,9.2,0
...,...,...,...,...,...,...,...,...,...,...,...
2820,Venezuela,South America,6.2,87,83,26.7,87,87,0.4,10.1,0
112,Vietnam,Asia,3.0,97,65,21.7,97,97,0.1,8.0,0
1706,"Yemen, Rep.",Middle East,0.0,69,95,23.7,63,69,0.0,3.0,0
1709,Zambia,Africa,3.5,90,47,22.5,90,90,4.5,6.9,0
1480,Zimbabwe,Africa,3.8,87,64,23.8,88,87,3.9,8.2,0

In [109]:
cd3

,Country,Birth Rate,GDP,Gross tertiary education enrollment (%),Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Population,Unemployment rate,Urban_population
0,Afghanistan,32.5,19101353833.0,9.7,47.9,64.5,638.0,0.3,38041754.0,11.1,9797273.0
1,Albania,11.8,15278077447.0,55.0,7.8,78.5,15.0,1.2,2854191.0,12.3,1747593.0
2,Algeria,24.3,169988236398.0,51.4,20.1,76.7,112.0,1.7,43053054.0,11.7,31510100.0
3,Andorra,7.2,3154057987.0,38.0,2.7,72.3,160.4,3.3,77142.0,6.9,67873.0
4,Angola,40.7,94635415870.0,9.3,51.6,60.8,241.0,0.2,31825295.0,6.9,21061025.0
...,...,...,...,...,...,...,...,...,...,...,...
190,Venezuela,17.9,482359318768.0,79.3,21.4,72.1,125.0,1.9,28515829.0,8.8,25162368.0
191,Vietnam,16.8,261921244843.0,28.5,16.5,75.3,43.0,0.8,96462106.0,2.0,35332140.0
192,Yemen,30.4,26914402224.0,10.2,42.9,66.1,164.0,0.3,29161922.0,12.9,10869523.0
193,Zambia,36.2,23064722446.0,4.1,40.4,63.5,213.0,1.2,17861030.0,11.4,7871713.0
194,Zimbabwe,30.7,21440758800.0,10.0,33.9,61.2,458.0,0.2,14645468.0,5.0,4717305.0

In [110]:
cd4

            Country Clean fuel %
0       Afghanistan         35.4
1           Albania         83.7
2           Algeria         99.7
3    American Samoa           ..
4           Andorra          100
..              ...          ...
207       Venezuela         95.5
208         Vietnam         96.1
209           Yemen         61.3
210          Zambia         10.2
211        Zimbabwe         30.3

[212 rows x 2 columns]

In [111]:
def merge_dataframes(df1, df2, df3, df4, country_column='Country'):
    # Step 1: Find the common set of countries
    common_countries = set(df1[country_column]) & set(df2[country_column]) & set(df3[country_column]) & set(df4[country_column])

    # Step 2: Select only the rows corresponding to common countries
    df1_common = df1[df1[country_column].isin(common_countries)]
    df2_common = df2[df2[country_column].isin(common_countries)]
    df3_common = df3[df3[country_column].isin(common_countries)]
    df4_common = df4[df4[country_column].isin(common_countries)]

    # Step 3: Merge DataFrames based on the common set of countries
    merged_df = pd.merge(df1_common, df2_common, on=country_column, how='inner')
    merged_df = pd.merge(merged_df, df3_common, on=country_column, how='inner')
    merged_df = pd.merge(merged_df, df4_common, on=country_column, how='inner')

    return merged_df

In [112]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [113]:
merged_data = merge_dataframes(cd1,cd2,cd3,cd4)
merged_data

,Country,health,income,inflation,Region,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,Schooling,Status,Birth Rate,GDP,Gross tertiary education enrollment (%),Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Population,Unemployment rate,Urban_population,Clean fuel %
0,Afghanistan,7.6,1610,9.4,Asia,0.0,65,42,23.3,67,65,0.0,3.6,0,32.5,19101353833.0,9.7,47.9,64.5,638.0,0.3,38041754.0,11.1,9797273.0,35.4
1,Albania,6.5,9930,4.5,Rest of Europe,4.3,99,98,26.6,99,99,0.0,9.7,0,11.8,15278077447.0,55.0,7.8,78.5,15.0,1.2,2854191.0,12.3,1747593.0,83.7
2,Algeria,4.2,12900,16.1,Africa,0.6,95,99,25.5,95,95,0.1,7.9,0,24.3,169988236398.0,51.4,20.1,76.7,112.0,1.7,43053054.0,11.7,31510100.0,99.7
3,Angola,2.9,5900,22.4,Africa,6.5,64,64,23.2,62,64,0.9,5.0,0,40.7,94635415870.0,9.3,51.6,60.8,241.0,0.2,31825295.0,6.9,21061025.0,50
4,Antigua and Barbuda,6.0,19100,1.4,Central America and Caribbean,9.1,99,84,26.6,86,99,0.2,9.2,0,15.3,1727759259.0,24.8,5.0,76.9,42.0,2.8,97118.0,6.9,23800.0,100
5,Argentina,8.1,18700,20.9,South America,8.5,94,87,27.6,93,94,0.1,9.8,0,17.0,449663446954.0,90.0,8.8,76.5,39.0,4.0,44938712.0,9.8,41339571.0,99.9
6,Armenia,4.4,6700,7.8,Rest of Europe,4.0,94,97,26.3,96,94,0.1,11.6,0,14.0,13672802158.0,54.6,11.0,74.9,26.0,4.4,2957731.0,17.0,1869848.0,98.4
7,Australia,8.7,41400,1.2,Oceania,9.7,93,93,27.1,93,93,0.0,12.8,1,12.6,1392680589329.0,113.1,3.1,82.7,6.0,3.7,25766605.0,5.3,21844756.0,100
8,Austria,11.0,43200,0.9,European Union,11.6,93,88,25.5,93,93,0.1,12.1,1,9.7,446314739528.0,85.1,2.9,81.6,5.0,5.2,8877067.0,4.7,5194416.0,100
9,Azerbaijan,5.9,16000,13.8,Asia,0.5,96,98,26.9,98,96,0.1,10.7,0,14.0,39207000000.0,27.7,19.2,72.9,26.0,3.5,10023318.0,5.5,5616165.0,98.3
10,Bahrain,5.0,41100,7.4,Middle East,1.5,98,99,24.8,98,98,0.1,9.3,0,14.0,38574069149.0,50.5,6.1,77.2,14.0,0.9,1501635.0,0.7,1467109.0,100
11,Bangladesh,3.5,2440,7.1,Asia,0.0,97,90,21.6,98,97,0.0,5.2,0,18.2,302571254131.0,20.6,25.1,72.3,173.0,0.6,167310838.0,4.2,60987417.0,26.5
12,Barbados,8.0,15300,0.3,Central America and Caribbean,9.7,97,89,27.7,97,97,0.3,10.5,0,10.7,5209000000.0,65.4,11.3,79.1,27.0,2.5,287025.0,10.3,89431.0,100
13,Belarus,5.6,16200,15.1,Rest of Europe,9.8,99,99,26.6,99,99,0.2,12.2,0,9.9,63080457023.0,87.4,2.6,74.2,2.0,5.2,9466856.0,4.6,7482982.0,99.6
14,Belgium,10.7,41100,1.9,European Union,10.4,98,85,26.1,99,99,0.1,11.7,1,10.3,529606710418.0,79.7,2.9,81.6,5.0,3.1,11484055.0,5.6,11259082.0,100
15,Belize,5.2,7880,1.1,Central America and Caribbean,6.7,94,95,28.9,94,94,0.4,10.5,0,20.8,1879613600.0,24.7,11.2,74.5,36.0,1.1,390353.0,6.4,179039.0,83
16,Benin,4.1,1820,0.9,Africa,1.5,82,83,23.5,72,82,0.3,3.5,0,36.2,14390709095.0,12.3,60.5,61.5,397.0,0.1,11801151.0,2.2,5648149.0,4.6
17,Bhutan,5.2,6420,6.0,Asia,0.0,99,94,23.8,98,99,0.1,3.1,0,17.3,2446674101.0,15.6,24.8,71.5,183.0,0.4,727145.0,2.3,317538.0,87
18,Bolivia,4.8,5410,8.8,South America,3.1,99,83,26.4,99,99,0.1,8.7,0,21.8,40895322865.0,38.0,21.8,71.2,155.0,1.6,11513100.0,3.5,8033035.0,88.3
19,Bosnia and Herzegovina,11.1,9720,1.4,Rest of Europe,4.9,82,88,25.7,74,82,0.1,9.0,0,8.1,20047848435.0,23.3,5.0,77.3,10.0,2.2,3301000.0,18.4,1605144.0,41.65
20,Botswana,8.3,13300,8.9,Africa,6.1,95,80,24.3,96,95,5.8,9.2,0,24.8,18340510789.0,24.9,30.0,69.3,144.0,0.4,2346179.0,18.2,1616550.0,65.7
21,Brazil,9.0,14500,8.4,South America,6.6,96,80,26.5,98,96,0.2,7.6,0,13.9,1839758040766.0,51.3,12.8,75.7,60.0,2.1,212559417.0,12.1,183241641.0,96.5
22,Bulgaria,6.9,15300,1.1,European Union,10.9,92,87,26.4,91,91,0.0,11.8,1,8.9,86000000000.0,71.0,5.9,74.9,10.0,4.0,6975761.0,4.3,5256027.0,..
23,Burkina Faso,6.7,1430,6.8,Africa,7.0,91,50,22.1,91,91,0.2,1.4,0,37.9,15745810235.0,6.5,49.0,61.2,320.0,0.1,20321378.0,6.3,6092349.0,11.7
24,Burundi,11.6,764,12.3,Africa,4.0,94,65,21.6,94,94,0.3,2.9,0,39.0,3012334882.0,6.1,41.0,61.2,548.0,0.1,11530580.0,1.4,1541177.0,0.2
25,Cambodia,5.7,2520,3.1,Asia,3.3,89,61,22.1,92,89,0.1,4.7,0,22.5,27089389787.0,13.7,24.0,69.6,160.0,0.2,16486542.0,0.7,3924621.0,44.5
26,Cameroon,5.1,2660,1.9,Africa,4.5,84,64,24.3,77,84,1.1,6.1,0,35.4,38760467033.0,12.8,50.6,58.9,529.0,0.1,25876380.0,3.4,14741256.0,22.8
27,Canada,11.3,40700,2.9,North America,8.0,55,86,26.9,91,91,0.1,13.1,1,10.1,1736425629520.0,68.9,4.3,81.9,10.0,2.6,36991981.0,5.6,30628482.0,100
28,Central African Republic,4.0,888,2.0,Africa,0.9,47,64,22.8,51,47,1.1,4.2,0,35.4,2220307369.0,3.0,84.5,52.8,829.0,0.1,4745185.0,3.7,1982064.0,0.900000000000001
29,Chad,4.5,1930,6.4,Africa,0.7,46,64,21.9,52,46,0.4,2.3,0,42.2,11314951343.0,3.3,71.4,54.0,1140.0,0.0,15946876.0,1.9,3712273.0,8
30,Chile,8.0,19400,9.0,South America,7.9,97,89,27.9,96,96,0.2,10.3,0,12.4,282318159745.0,88.5,6.2,80.0,13.0,2.6,18952038.0,7.1,16610135.0,100
31,China,5.1,9530,6.9,Asia,5.7,99,99,23.7,99,99,0.1,7.7,0,10.9,19910000000000.0,50.6,7.4,77.0,29.0,2.0,1397715000.0,4.3,842933962.0,83.2
32,Colombia,7.6,10900,3.9,South America,4.2,91,86,26.1,91,91,0.2,8.1,0,14.9,323802808108.0,55.3,12.2,77.1,83.0,2.2,50339443.0,9.7,40827302.0,93.3
33,Comoros,4.5,1410,3.9,Africa,0.1,91,64,24.3,92,91,0.0,4.8,0,31.9,1185728677.0,9.0,51.3,64.1,273.0,0.3,850886.0,4.3,248152.0,11.3
34,Costa Rica,10.9,13000,6.6,Central America and Caribbean,3.2,92,90,27.3,92,92,0.2,8.8,0,14.0,61773944174.0,55.2,7.6,80.1,27.0,2.9,5047561.0,11.8,4041885.0,95.9
35,Croatia,7.8,20100,0.8,European Union,9.6,94,96,27.3,94,94,0.0,11.2,1,9.0,60415553039.0,67.9,4.0,78.1,8.0,3.0,4067500.0,6.9,2328318.0,100
36,Cyprus,6.0,33900,2.0,European Union,9.6,97,88,26.8,97,97,0.1,11.9,1,10.5,24564647935.0,75.9,1.9,80.8,6.0,1.9,1198575.0,7.3,800708.0,100
37,Denmark,11.4,44000,3.2,European Union,9.4,88,80,25.3,93,93,0.0,12.5,1,10.6,348078018464.0,80.6,3.6,81.0,4.0,4.0,5818553.0,4.9,5119978.0,100
38,Dominican Republic,6.2,11100,5.4,Central America and Caribbean,5.4,81,83,26.4,87,85,0.4,7.8,0,19.5,88941298258.0,59.9,24.1,73.9,95.0,1.6,10738958.0,5.8,8787475.0,91.5
39,Ecuador,8.1,9350,7.5,South America,3.7,78,76,27.1,84,78,0.2,8.4,0,19.7,107435665000.0,44.9,12.2,76.8,59.0,2.0,17373662.0,4.0,11116711.0,94.7
40,El Salvador,6.9,7300,2.6,Central America and Caribbean,2.5,91,88,27.6,92,91,0.2,6.6,0,18.2,27022640000.0,29.4,11.8,73.1,46.0,1.6,6453553.0,4.1,4694702.0,92.7
41,Equatorial Guinea,4.5,33700,24.9,Africa,8.1,40,64,23.9,37,16,4.2,5.5,0,33.2,11026774945.0,1.9,62.6,58.4,301.0,0.4,1355986.0,6.4,984812.0,24.1
42,Eritrea,2.7,1420,11.6,Africa,1.0,95,88,20.7,95,95,0.1,3.9,0,30.3,2065001626.0,3.4,31.3,65.9,480.0,0.1,6333135.0,5.1,1149670.0,11.5
43,Estonia,6.0,22700,1.7,European Union,16.7,91,92,26.4,93,93,0.1,12.7,1,10.9,31386949981.0,69.6,2.1,78.2,9.0,4.5,1331824.0,5.1,916024.0,100
44,Fiji,4.9,7350,4.2,Oceania,2.6,99,94,27.6,99,99,0.1,10.8,0,21.3,5535548972.0,16.1,21.6,67.3,34.0,0.8,889953.0,4.1,505048.0,51.4
45,Finland,8.9,39800,0.4,European Union,8.5,88,92,25.9,97,97,0.1,12.4,1,8.6,268761201365.0,88.2,1.4,81.7,3.0,3.8,5520314.0,6.6,4716888.0,100
46,France,11.9,36900,1.1,European Union,11.9,86,79,25.0,97,98,0.1,11.5,1,11.3,2715518274227.0,65.6,3.4,82.5,8.0,3.3,67059887.0,8.4,54123364.0,100
47,Gabon,3.5,15400,16.6,Africa,8.1,80,64,25.2,79,80,1.1,8.1,0,31.6,16657960228.0,8.3,32.7,66.2,252.0,0.7,2172579.0,20.0,1949694.0,89.7
48,Georgia,10.1,6730,8.6,Rest of Europe,7.0,94,91,27.5,91,94,0.1,12.7,0,13.5,17743195770.0,63.9,8.7,73.6,25.0,7.1,3720382.0,14.4,2196476.0,90.6
49,Germany,11.6,40400,0.8,European Union,11.1,88,93,26.5,92,95,0.0,14.1,1,9.5,3845630030824.0,70.2,3.1,80.9,7.0,4.2,83132799.0,3.0,64324835.0,100
50,Ghana,5.2,3060,16.6,Africa,1.8,88,63,23.9,88,88,0.8,6.9,0,29.4,66983634224.0,15.7,34.9,63.8,308.0,0.1,30792608.0,4.3,17249054.0,30.3
51,Greece,10.3,28700,0.7,European Union,6.7,96,83,27.1,99,99,0.1,10.6,1,8.1,209852761469.0,136.6,3.6,81.3,3.0,5.5,10716322.0,17.2,8507474.0,100
52,Grenada,5.9,11200,0.5,Central America and Caribbean,8.2,92,89,26.9,99,92,0.4,8.7,0,16.5,1228170370.0,104.6,13.7,72.4,25.0,1.4,112003.0,6.9,40765.0,88.3
53,Guatemala,6.8,6710,5.1,Central America and Caribbean,1.6,74,83,26.5,69,74,0.0,6.3,0,24.6,76710385880.0,21.8,22.1,74.1,95.0,0.3,16604026.0,2.5,8540945.0,48.1
54,Guinea,4.9,1190,16.1,Africa,0.4,54,64,22.9,47,54,0.7,2.6,0,36.4,13590281809.0,11.6,64.9,61.2,576.0,0.1,12771246.0,4.3,4661505.0,1
55,Guinea-Bissau,8.5,1390,3.0,Africa,3.1,87,64,23.4,83,87,1.6,2.9,0,35.1,1340389411.0,2.6,54.0,58.0,667.0,0.1,1920922.0,2.5,840922.0,1
56,Guyana,5.4,5840,5.7,South America,5.5,95,95,26.3,92,95,0.6,8.4,0,20.0,4280443645.0,11.6,25.1,69.8,169.0,0.8,782766.0,11.8,208912.0,82
57,Haiti,6.9,1500,5.5,Central America and Caribbean,2.8,64,83,25.2,64,60,0.7,5.2,0,24.4,8498981821.0,1.1,49.5,63.7,480.0,0.2,11263077.0,13.8,6328948.0,4.3
58,Hungary,7.3,22300,2.3,European Union,10.9,88,99,27.2,99,99,0.1,11.8,1,9.6,160967157504.0,48.5,3.6,75.8,12.0,3.4,9769949.0,3.4,6999582.0,100
59,Iceland,9.4,38800,5.5,Rest of Europe,7.7,88,94,26.2,92,92,0.1,12.2,1,12.0,24188035739.0,71.8,1.5,82.7,4.0,4.1,361313.0,2.8,339110.0,100
60,India,4.0,4410,9.0,Asia,3.0,87,69,21.7,86,87,0.1,6.3,0,17.9,2611000000000.0,28.1,29.9,69.4,145.0,0.9,1366417754.0,5.4,471031528.0,71.1
61,Indonesia,2.6,8430,15.3,Asia,0.1,78,31,23.0,85,78,0.1,7.9,0,18.1,1119190780753.0,36.3,21.1,71.5,177.0,0.4,270203917.0,4.7,151509724.0,86.9
62,Iraq,8.4,12700,16.6,Middle East,0.2,56,76,28.6,72,58,0.1,6.6,0,29.1,234094042939.0,16.2,22.5,70.5,79.0,0.7,39309783.0,12.8,27783368.0,99.3
63,Israel,7.6,29600,1.8,Middle East,2.7,96,97,27.2,95,95,0.1,13.0,1,20.8,395098666122.0,63.4,3.0,82.8,3.0,4.6,9053300.0,3.9,8374393.0,100
64,Italy,9.5,36200,0.3,European Union,7.1,93,83,25.6,93,93,0.1,10.2,1,7.3,2001244392042.0,61.9,2.6,82.9,2.0,4.0,60297396.0,9.9,42651966.0,100
65,Jamaica,4.8,8000,9.8,Central America and Caribbean,3.3,91,83,27.6,91,91,0.5,9.6,0,16.1,16458071068.0,27.1,12.4,74.4,80.0,1.3,2948279.0,8.0,1650594.0,82.5
66,Japan,9.5,35800,-1.9,Asia,8.6,83,93,22.7,99,96,0.2,12.5,1,7.4,5081769542380.0,63.2,1.8,84.2,5.0,2.4,126226568.0,2.3,115782416.0,100
67,Jordan,8.0,9470,8.4,Middle East,0.3,99,96,28.9,99,99,0.1,10.3,0,22.0,43743661972.0,34.4,13.9,74.4,46.0,2.3,10101694.0,14.7,9213048.0,99.9
68,Kazakhstan,4.3,20100,19.5,Asia,3.3,98,98,26.3,98,98,0.1,11.7,0,21.8,180161741180.0,61.7,8.8,73.2,10.0,3.2,18513930.0,4.6,10652915.0,93.9
69,Kenya,4.8,2480,2.1,Africa,1.6,89,28,23.3,83,89,1.1,6.3,0,28.8,95503088538.0,11.5,30.6,66.3,342.0,0.2,52573973.0,2.6,14461523.0,23.9
70,Kiribati,11.3,1730,1.5,Oceania,0.3,82,76,30.0,80,78,0.2,7.9,0,27.9,194647202.0,38.0,41.2,68.1,92.0,0.2,117606.0,6.9,64489.0,12.4
71,Kuwait,2.6,75200,11.2,Middle East,0.0,99,96,29.5,99,99,0.1,7.1,0,13.9,134761198946.0,54.4,6.7,75.4,12.0,2.6,4207083.0,2.2,4207083.0,100
72,Latvia,6.7,18300,-0.8,European Union,10.8,94,92,26.6,94,95,0.3,12.8,1,10.0,34117202555.0,88.1,3.3,74.7,19.0,3.2,1912789.0,6.5,1304943.0,100
73,Lebanon,7.0,16300,0.2,Middle East,1.1,81,63,27.5,81,81,0.0,8.5,0,17.6,53367042272.0,26.3,6.4,78.9,29.0,2.1,6855713.0,6.2,6084994.0,..
74,Lesotho,11.1,2380,4.2,Africa,3.1,93,82,24.9,85,93,10.0,6.1,0,26.8,2460072444.0,10.2,65.7,53.7,544.0,0.1,2125268.0,23.4,607508.0,41.1
75,Liberia,11.8,700,5.5,Africa,3.2,52,64,24.0,65,52,3.5,4.4,0,33.0,3070518100.0,11.9,53.5,63.7,661.0,0.0,4937374.0,2.8,2548426.0,0.4
76,Libya,3.9,29600,14.2,Africa,0.0,97,97,28.0,97,97,0.1,7.3,0,18.8,52076250948.0,60.5,10.2,72.7,72.0,2.1,6777452.0,18.6,5448597.0,..
77,Lithuania,7.0,21100,2.4,European Union,14.2,94,92,26.4,93,93,0.1,13.0,1,10.0,54219315600.0,72.4,3.3,75.7,8.0,6.3,2786844.0,6.3,1891013.0,100
78,Luxembourg,7.8,91700,3.6,European Union,11.4,94,86,26.3,99,99,0.1,12.0,1,10.3,71104919108.0,19.2,1.9,82.1,5.0,3.0,645397.0,5.4,565488.0,100
79,Madagascar,3.8,1390,8.8,Africa,0.9,69,64,21.3,68,69,0.2,6.1,0,32.7,14083906357.0,5.4,38.2,66.7,335.0,0.2,26969307.0,1.8,10210849.0,1.4
80,Malawi,6.6,1030,12.1,Africa,2.0,88,64,22.8,88,88,2.6,4.4,0,34.1,7666704427.0,0.8,35.3,63.8,349.0,0.0,18628747.0,5.7,3199301.0,1.6
81,Malaysia,4.4,21100,7.3,Asia,0.6,99,99,25.6,99,99,0.1,10.2,0,16.8,364701517788.0,45.1,6.7,76.0,29.0,1.5,32447385.0,3.3,24475766.0,93.8
82,Maldives,6.3,10500,2.9,Asia,1.3,99,99,25.3,99,99,0.2,6.3,0,14.2,5729248472.0,31.2,7.4,78.6,53.0,4.6,530953.0,6.1,213645.0,99.5
83,Mali,5.0,1870,4.4,Africa,0.6,64,64,22.9,67,64,0.4,2.3,0,41.5,17510141171.0,4.5,62.0,58.9,562.0,0.1,19658031.0,7.2,8479688.0,0.900000000000001
84,Malta,8.7,28300,3.8,European Union,7.4,95,91,27.1,97,97,0.1,11.2,1,9.2,14786156563.0,54.3,6.1,82.3,6.0,2.9,502653.0,3.5,475902.0,100
85,Mauritania,4.4,3320,18.9,Africa,0.0,73,64,24.9,67,73,0.1,4.3,0,33.7,7593752450.0,5.0,51.5,64.7,766.0,0.2,4525696.0,9.6,2466821.0,48.3
86,Mauritius,6.0,15900,1.1,Africa,2.8,97,96,25.2,98,97,0.7,9.1,0,10.2,14180444557.0,40.6,13.6,74.4,61.0,2.5,1265711.0,6.7,515980.0,98.9
87,Moldova,11.7,3910,11.1,Rest of Europe,6.8,88,92,27.0,88,87,0.4,11.6,0,10.1,11955435457.0,39.8,13.6,71.8,19.0,3.2,2657637.0,5.5,1135502.0,97.6
88,Mongolia,5.4,7710,39.2,Asia,8.3,99,98,26.1,99,99,0.0,10.1,0,24.1,13852850259.0,65.6,14.0,69.7,45.0,2.9,3225167.0,6.0,2210626.0,53
89,Montenegro,9.1,14000,1.6,Rest of Europe,8.5,82,94,26.5,89,89,0.0,11.3,0,11.7,5494736901.0,56.1,2.3,76.8,6.0,2.8,622137.0,14.9,417765.0,62
90,Morocco,5.2,6440,1.0,Africa,0.4,99,95,25.9,99,99,0.0,5.0,0,18.9,118725279596.0,35.9,19.2,76.5,70.0,0.7,36910560.0,9.0,22975026.0,98.2
91,Mozambique,5.2,918,7.6,Africa,1.2,88,64,22.7,88,80,3.5,3.5,0,37.5,14934159926.0,7.3,54.0,60.2,289.0,0.1,30366036.0,3.2,11092106.0,5.4
92,Myanmar,2.0,3720,7.0,Asia,1.5,89,78,22.6,89,89,0.3,4.9,0,17.6,76085852617.0,18.8,36.8,66.9,250.0,0.7,54045420.0,1.6,16674093.0,43.5
93,Namibia,6.8,8460,3.6,Africa,2.6,92,64,24.2,92,92,4.6,6.7,0,28.6,12366527719.0,22.9,29.0,63.4,195.0,0.4,2494530.0,20.3,1273258.0,47.3
94,Nepal,5.2,1990,15.1,Asia,0.2,91,65,22.4,90,91,0.2,4.7,0,19.9,30641380604.0,12.4,26.7,70.5,186.0,0.8,28608710.0,1.4,5765513.0,35.2
95,Netherlands,11.9,45500,0.8,European Union,8.3,94,92,25.5,95,95,0.0,12.1,1,9.7,909070395161.0,85.0,3.3,81.8,5.0,3.6,17332850.0,3.2,15924729.0,100
96,New Zealand,10.1,32300,3.7,Oceania,8.7,92,87,28.0,92,92,0.0,12.4,1,12.0,206928765544.0,82.0,4.7,81.9,9.0,3.6,4841000.0,4.1,4258860.0,100
97,Niger,5.2,814,2.5,Africa,0.1,65,64,21.8,83,65,0.1,1.8,0,46.1,12928145120.0,4.4,48.0,62.0,509.0,0.0,23310715.0,0.5,3850231.0,3
98,Nigeria,5.1,5150,104.0,Africa,4.5,49,64,23.2,42,49,0.6,6.0,0,37.9,448120428859.0,10.2,75.7,54.3,917.0,0.4,200963599.0,8.1,102806948.0,16.8
99,Norway,9.5,62300,6.0,Rest of Europe,6.0,88,91,26.6,95,95,0.0,12.5,1,10.4,403336363636.0,82.0,2.1,82.8,2.0,2.9,5347896.0,3.4,4418218.0,100
100,Oman,2.8,45300,15.6,Middle East,0.5,99,98,26.3,99,99,0.1,9.5,0,19.2,76983094928.0,38.0,9.8,77.6,19.0,2.0,5266535.0,2.7,4250777.0,100
101,Pakistan,2.2,4280,10.9,Asia,0.0,72,54,23.9,72,72,0.1,5.1,0,28.2,304400000000.0,9.0,57.2,67.1,140.0,1.0,216565318.0,4.5,79927762.0,50.7
102,Panama,8.1,15400,2.6,Central America and Caribbean,6.8,73,92,26.8,72,73,0.4,9.9,0,19.0,66800800000.0,47.8,13.1,78.3,52.0,1.6,4246439.0,3.9,2890084.0,100
103,Paraguay,5.9,7290,6.1,South America,5.2,93,72,26.6,93,93,0.1,8.5,0,20.6,38145288940.0,34.6,17.2,74.1,129.0,1.4,7044636.0,4.8,4359150.0,69.8
104,Peru,5.1,9960,5.7,South America,5.7,90,63,26.5,88,90,0.1,9.1,0,17.9,226848050820.0,70.7,11.1,76.5,88.0,1.3,32510453.0,3.3,25390339.0,85.5
105,Philippines,3.6,5600,4.2,Asia,4.5,75,57,23.1,79,60,0.1,9.3,0,20.6,376795508680.0,35.5,22.5,71.1,121.0,0.6,108116615.0,2.1,50975903.0,48
106,Poland,7.5,21800,1.7,European Union,10.5,96,94,26.6,92,98,0.1,12.1,1,10.2,592164400688.0,67.8,3.8,77.6,2.0,2.4,37970874.0,3.5,22796574.0,100
107,Portugal,11.0,27200,0.6,European Union,10.3,98,95,25.7,98,98,0.1,9.1,1,8.5,237686075635.0,63.9,3.1,81.3,8.0,5.1,10269417.0,6.3,6753579.0,100
108,Qatar,1.8,125000,7.0,Middle East,1.0,99,91,29.1,99,99,0.1,9.8,0,9.5,183466208791.0,17.9,5.8,80.1,9.0,2.5,2832067.0,0.1,2809071.0,100
109,Romania,5.6,17800,3.5,European Union,9.4,90,80,26.7,89,89,0.0,10.9,1,9.6,250077444017.0,49.4,6.1,75.4,19.0,3.0,19356544.0,4.0,10468793.0,100
110,Russia,5.1,23100,14.2,Rest of Europe,8.1,97,97,26.2,97,97,0.1,12.0,0,11.5,1699876578871.0,81.9,6.1,72.7,17.0,4.0,144373535.0,4.6,107683889.0,72.9
111,Rwanda,10.5,1350,2.6,Africa,6.3,98,87,22.0,99,98,0.6,4.0,0,31.7,10122472590.0,6.7,27.0,68.7,248.0,0.1,12626950.0,1.0,2186104.0,5.4
112,Samoa,6.5,5400,1.7,Oceania,2.1,59,55,32.1,78,66,0.2,10.3,0,24.4,850655017.0,7.6,13.6,73.2,43.0,0.3,202506.0,8.4,35588.0,37.2
113,Saudi Arabia,4.3,45400,17.2,Middle East,0.0,98,96,28.4,97,98,0.1,9.5,0,17.8,792966838162.0,68.0,6.0,75.0,17.0,2.6,34268528.0,5.9,28807838.0,100
114,Senegal,5.7,2180,1.9,Africa,0.2,89,54,22.9,85,89,0.1,2.9,0,34.5,23578084052.0,12.8,31.8,67.7,315.0,0.1,16296364.0,6.6,7765706.0,29.4
115,Serbia,10.4,12700,5.9,Rest of Europe,7.2,94,86,26.0,95,95,0.0,11.0,0,9.2,51409167351.0,67.2,4.8,75.5,12.0,3.1,6944975.0,12.7,3907243.0,80.6
116,Seychelles,3.4,20400,-4.2,Africa,8.7,98,98,26.6,97,97,3.5,9.5,0,17.1,1698843063.0,17.1,12.4,72.8,53.0,0.9,97625.0,6.9,55762.0,100
117,Sierra Leone,13.1,1220,17.2,Africa,3.1,86,60,22.7,86,86,0.8,3.4,0,33.4,3941474311.0,2.0,78.5,54.3,1120.0,0.0,7813215.0,4.4,3319366.0,0.800000000000001
118,Singapore,4.0,72100,-0.0,Asia,1.8,96,90,23.6,96,96,0.1,11.5,0,8.8,372062527489.0,84.8,2.3,83.1,8.0,2.3,5703569.0,4.1,5703569.0,100
119,Slovenia,9.4,28700,-1.0,European Union,11.5,88,96,26.5,95,95,0.0,12.0,1,9.4,53742159517.0,78.6,1.7,81.0,7.0,3.1,2087946.0,4.2,1144654.0,100
120,Solomon Islands,8.6,1780,6.8,Oceania,1.0,98,65,26.2,85,98,0.2,5.4,0,32.4,1425074226.0,38.0,17.1,72.8,104.0,0.2,669823.0,0.6,162164.0,8.9
121,South Africa,8.9,12000,6.3,Africa,7.2,75,59,27.2,85,75,6.9,10.1,0,20.5,351431649241.0,22.4,28.5,63.9,119.0,0.9,58558270.0,28.2,39149717.0,88.4
122,Spain,9.5,32500,0.2,European Union,10.3,97,94,26.0,97,97,0.1,9.7,1,7.9,1394116310769.0,88.9,2.5,83.3,4.0,3.9,47076781.0,14.0,37927409.0,100
123,Sri Lanka,2.9,8560,22.8,Asia,2.7,99,99,23.0,99,99,0.0,10.9,0,15.8,84008783756.0,19.6,6.4,76.8,36.0,1.0,21803000.0,4.2,4052088.0,32.6
124,Suriname,7.0,14200,7.2,South America,4.8,89,21,26.5,78,89,0.5,8.4,0,18.5,3985250737.0,12.6,16.9,71.6,120.0,1.2,581372.0,7.3,384258.0,94.8
125,Sweden,9.6,42900,1.0,European Union,7.1,67,95,26.0,98,98,0.1,12.4,1,11.4,530832908738.0,67.0,2.2,82.5,4.0,4.0,10285453.0,6.5,9021165.0,100
126,Switzerland,11.5,55500,0.3,Rest of Europe,9.6,88,87,25.2,96,97,0.1,13.4,1,10.0,703082435360.0,59.6,3.7,83.6,5.0,4.3,8574832.0,4.6,6332428.0,100
127,Tajikistan,6.0,2110,12.5,Asia,0.9,96,94,25.9,96,96,0.1,10.5,0,30.8,8116626794.0,31.3,30.4,70.9,17.0,1.7,9321018.0,11.0,2545477.0,85.5
128,Tanzania,6.0,2090,9.2,Africa,7.9,98,64,23.1,96,98,2.0,5.8,0,36.7,63177068175.0,4.0,37.6,65.0,524.0,0.0,58005463.0,2.0,20011885.0,6.9
129,Thailand,3.9,13500,4.1,Asia,7.0,99,95,24.3,99,99,0.2,7.6,0,10.3,543649976166.0,49.3,7.8,76.9,37.0,0.8,69625582.0,0.8,35294600.0,85.1
130,Togo,7.7,1210,1.2,Africa,1.4,88,64,23.5,82,88,0.7,4.7,0,33.1,5459979417.0,14.5,47.4,60.8,396.0,0.1,8082366.0,2.0,3414638.0,11.4
131,Tonga,5.1,4980,3.7,Oceania,0.2,78,99,32.1,96,78,0.2,11.2,0,24.3,450353314.0,6.4,13.4,70.8,52.0,0.5,100209.0,1.1,24145.0,86.8
132,Tunisia,6.2,10400,3.8,Africa,1.5,98,98,26.3,98,98,0.0,7.0,0,17.6,38797709924.0,31.7,14.6,76.5,43.0,1.3,11694719.0,16.0,8099061.0,99.9
133,Turkey,6.7,18000,7.0,Middle East,1.3,97,65,27.8,97,97,0.1,7.8,0,16.0,754411708203.0,23.9,9.1,77.4,17.0,1.9,83429615.0,13.5,63097818.0,95.4
134,Turkmenistan,2.5,9940,2.3,Asia,3.4,99,99,26.4,99,99,0.1,9.8,0,23.8,40761142857.0,8.0,39.3,68.1,7.0,2.2,5942089.0,3.9,3092738.0,99.9
135,Uganda,9.0,1540,10.6,Africa,7.4,78,64,22.4,85,78,2.1,5.7,0,38.1,34387229486.0,4.8,33.8,63.0,375.0,0.2,44269594.0,1.8,10784516.0,0.700000000000001
136,Ukraine,7.7,7820,13.4,Rest of Europe,6.0,22,57,26.5,51,23,0.2,11.3,0,8.7,153781069118.0,82.7,7.5,71.6,19.0,3.0,44385155.0,8.9,30835699.0,95.2
137,United Arab Emirates,3.7,57600,12.5,Middle East,2.1,99,99,28.4,99,99,0.1,10.6,0,10.3,421142267938.0,36.8,6.5,77.8,3.0,2.5,9770529.0,2.4,8479744.0,100
138,United Kingdom,9.6,36200,1.6,Rest of Europe,9.6,88,86,27.1,96,96,0.1,12.8,1,11.0,2827113184696.0,60.0,3.6,81.3,7.0,2.8,66834405.0,3.9,55908316.0,100

In [114]:
unique_countries = merged_data['Country'].unique()
print(unique_countries)

['Afghanistan' 'Albania' 'Algeria' 'Angola' 'Antigua and Barbuda'
 'Argentina' 'Armenia' 'Australia' 'Austria' 'Azerbaijan' 'Bahrain'
 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin' 'Bhutan'
 'Bolivia' 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'Bulgaria'
 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon' 'Canada'
 'Central African Republic' 'Chad' 'Chile' 'China' 'Colombia' 'Comoros'
 'Costa Rica' 'Croatia' 'Cyprus' 'Denmark' 'Dominican Republic' 'Ecuador'
 'El Salvador' 'Equatorial Guinea' 'Eritrea' 'Estonia' 'Fiji' 'Finland'
 'France' 'Gabon' 'Georgia' 'Germany' 'Ghana' 'Greece' 'Grenada'
 'Guatemala' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti' 'Hungary' 'Iceland'
 'India' 'Indonesia' 'Iraq' 'Israel' 'Italy' 'Jamaica' 'Japan' 'Jordan'
 'Kazakhstan' 'Kenya' 'Kiribati' 'Kuwait' 'Latvia' 'Lebanon' 'Lesotho'
 'Liberia' 'Libya' 'Lithuania' 'Luxembourg' 'Madagascar' 'Malawi'
 'Malaysia' 'Maldives' 'Mali' 'Malta' 'Mauritania' 'Mauritius' 'Moldova'
 'Mongolia' 'Montenegro' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia'
 'Nepal' 'Netherlands' 'New Zealand' 'Niger' 'Nigeria' 'Norway' 'Oman'
 'Pakistan' 'Panama' 'Paraguay' 'Peru' 'Philippines' 'Poland' 'Portugal'
 'Qatar' 'Romania' 'Russia' 'Rwanda' 'Samoa' 'Saudi Arabia' 'Senegal'
 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore' 'Slovenia'
 'Solomon Islands' 'South Africa' 'Spain' 'Sri Lanka' 'Suriname' 'Sweden'
 'Switzerland' 'Tajikistan' 'Tanzania' 'Thailand' 'Togo' 'Tonga' 'Tunisia'
 'Turkey' 'Turkmenistan' 'Uganda' 'Ukraine' 'United Arab Emirates'
 'United Kingdom' 'United States' 'Uruguay' 'Uzbekistan' 'Vanuatu'
 'Venezuela' 'Vietnam' 'Zambia']

In [115]:
unique_countries = merged_data['Region'].unique()
print(unique_countries)

['Asia' 'Rest of Europe' 'Africa' 'Central America and Caribbean'
 'South America' 'Oceania' 'European Union' 'Middle East' 'North America']

In [116]:
merged_data.isnull().sum()

Country                                    0
health                                     0
income                                     0
inflation                                  0
Region                                     0
Alcohol_consumption                        0
Hepatitis_B                                0
Measles                                    0
BMI                                        0
Polio                                      0
Diphtheria                                 0
Incidents_HIV                              0
Schooling                                  0
Status                                     0
Birth Rate                                 0
GDP                                        0
Gross tertiary education enrollment (%)    0
Infant mortality                           0
Life expectancy                            0
Maternal mortality ratio                   0
Physicians per thousand                    0
Population                                 0
Unemployment rate                          0
Urban_population                           0
Clean fuel %                               0
dtype: int64

In [117]:
(merged_data == 0).sum()

Country                                      0
health                                       0
income                                       0
inflation                                    0
Region                                       0
Alcohol_consumption                          4
Hepatitis_B                                  0
Measles                                      0
BMI                                          0
Polio                                        0
Diphtheria                                   0
Incidents_HIV                                0
Schooling                                    0
Status                                     112
Birth Rate                                   0
GDP                                          0
Gross tertiary education enrollment (%)      0
Infant mortality                             0
Life expectancy                              0
Maternal mortality ratio                     0
Physicians per thousand                      0
Population                                   0
Unemployment rate                            0
Urban_population                             0
Clean fuel %                                 0
dtype: int64

In [118]:
print(merged_data.columns)

Index(['Country', 'health', 'income', 'inflation', 'Region',
       'Alcohol_consumption', 'Hepatitis_B', 'Measles', 'BMI', 'Polio',
       'Diphtheria', 'Incidents_HIV', 'Schooling', 'Status', 'Birth Rate',
       'GDP', 'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Life expectancy', 'Maternal mortality ratio',
       'Physicians per thousand', 'Population', 'Unemployment rate',
       'Urban_population', 'Clean fuel %'],
      dtype='object')

In [119]:
merged_data['GDP per capita']=merged_data['GDP']/merged_data['Population']

In [120]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 146 entries, 0 to 145
Data columns (total 26 columns):
 #   Column                                   Non-Null Count  Dtype
---  ------                                   --------------  -----
 0   Country                                  146 non-null    object
 1   health                                   146 non-null    float64
 2   income                                   146 non-null    int64
 3   inflation                                146 non-null    float64
 4   Region                                   146 non-null    object
 5   Alcohol_consumption                      146 non-null    float64
 6   Hepatitis_B                              146 non-null    int64
 7   Measles                                  146 non-null    int64
 8   BMI                                      146 non-null    float64
 9   Polio                                    146 non-null    int64
 10  Diphtheria                               146 non-null    int64
 11  Incidents_HIV                            146 non-null    float64
 12  Schooling                                146 non-null    float64
 13  Status                                   146 non-null    int64
 14  Birth Rate                               146 non-null    float64
 15  GDP                                      146 non-null    float64
 16  Gross tertiary education enrollment (%)  146 non-null    float64
 17  Infant mortality                         146 non-null    float64
 18  Life expectancy                          146 non-null    float64
 19  Maternal mortality ratio                 146 non-null    float64
 20  Physicians per thousand                  146 non-null    float64
 21  Population                               146 non-null    float64
 22  Unemployment rate                        146 non-null    float64
 23  Urban_population                         146 non-null    float64
 24  Clean fuel %                             146 non-null    object
 25  GDP per capita                           146 non-null    float64
dtypes: float64(17), int64(6), object(3)
memory usage: 29.8+ KB

In [121]:
print(merged_data.columns)

Index(['Country', 'health', 'income', 'inflation', 'Region',
       'Alcohol_consumption', 'Hepatitis_B', 'Measles', 'BMI', 'Polio',
       'Diphtheria', 'Incidents_HIV', 'Schooling', 'Status', 'Birth Rate',
       'GDP', 'Gross tertiary education enrollment (%)', 'Infant mortality',
       'Life expectancy', 'Maternal mortality ratio',
       'Physicians per thousand', 'Population', 'Unemployment rate',
       'Urban_population', 'Clean fuel %', 'GDP per capita'],
      dtype='object')

In [122]:
merged_data.describe()

,health,income,inflation,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,Schooling,Status,Birth Rate,GDP,Gross tertiary education enrollment (%),Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Population,Unemployment rate,Urban_population,GDP per capita
count,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0,146.0
mean,6.9,17436.3,7.6,4.9,87.2,80.9,25.6,88.8,88.2,0.6,8.6,0.2,19.9,593733873000.1,40.6,20.5,72.7,149.5,1.9,46633267.8,6.7,26025837.3,14944.6
std,2.8,19325.7,10.8,3.8,14.1,16.5,2.2,12.5,14.7,1.3,3.1,0.4,9.9,2480509769391.0,29.9,19.6,7.5,225.7,1.6,165784174.7,5.0,85083372.3,19911.8
min,1.8,700.0,-4.2,0.0,22.0,21.0,20.7,37.0,16.0,0.0,1.4,0.0,7.3,194647202.0,0.8,1.4,52.8,2.0,0.0,97118.0,0.1,23800.0,261.2
25%,4.9,3767.5,1.8,1.4,84.5,64.0,23.8,85.0,87.0,0.1,6.1,0.0,10.9,13717814183.2,12.4,5.6,67.8,10.0,0.4,2950642.0,3.4,1778156.8,1965.0
50%,6.4,10700.0,5.3,4.2,92.0,86.5,26.1,93.0,94.0,0.1,9.1,0.0,17.8,53554600894.5,36.1,12.9,74.2,43.0,1.6,10062506.0,5.3,5532381.0,6326.2
75%,8.7,22600.0,9.7,8.0,97.0,94.0,26.9,97.0,97.0,0.4,11.3,0.0,28.2,297507980534.5,65.0,30.3,78.0,181.5,3.0,32291862.5,8.4,16870320.0,17693.2
max,17.9,125000.0,104.0,16.7,99.0,99.0,32.1,99.0,99.0,10.0,14.1,1.0,46.1,21427700000000.0,136.6,84.5,84.2,1140.0,7.1,1397715000.0,28.2,842933962.0,110172.4

In [123]:
merged_data.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
health,146.0,6.9,2.8,1.8,4.9,6.4,8.7,17.9
income,146.0,17436.3,19325.7,700.0,3767.5,10700.0,22600.0,125000.0
inflation,146.0,7.6,10.8,-4.2,1.8,5.3,9.7,104.0
Alcohol_consumption,146.0,4.9,3.8,0.0,1.4,4.2,8.0,16.7
Hepatitis_B,146.0,87.2,14.1,22.0,84.5,92.0,97.0,99.0
Measles,146.0,80.9,16.5,21.0,64.0,86.5,94.0,99.0
BMI,146.0,25.6,2.2,20.7,23.8,26.1,26.9,32.1
Polio,146.0,88.8,12.5,37.0,85.0,93.0,97.0,99.0
Diphtheria,146.0,88.2,14.7,16.0,87.0,94.0,97.0,99.0
Incidents_HIV,146.0,0.6,1.3,0.0,0.1,0.1,0.4,10.0
Schooling,146.0,8.6,3.1,1.4,6.1,9.1,11.3,14.1
Status,146.0,0.2,0.4,0.0,0.0,0.0,0.0,1.0
Birth Rate,146.0,19.9,9.9,7.3,10.9,17.8,28.2,46.1
GDP,146.0,593733873000.1,2480509769391.0,194647202.0,13717814183.2,53554600894.5,297507980534.5,21427700000000.0
Gross tertiary education enrollment (%),146.0,40.6,29.9,0.8,12.4,36.1,65.0,136.6
Infant mortality,146.0,20.5,19.6,1.4,5.6,12.9,30.3,84.5
Life expectancy,146.0,72.7,7.5,52.8,67.8,74.2,78.0,84.2
Maternal mortality ratio,146.0,149.5,225.7,2.0,10.0,43.0,181.5,1140.0
Physicians per thousand,146.0,1.9,1.6,0.0,0.4,1.6,3.0,7.1
Population,146.0,46633267.8,165784174.7,97118.0,2950642.0,10062506.0,32291862.5,1397715000.0
Unemployment rate,146.0,6.7,5.0,0.1,3.4,5.3,8.4,28.2
Urban_population,146.0,26025837.3,85083372.3,23800.0,1778156.8,5532381.0,16870320.0,842933962.0
GDP per capita,146.0,14944.6,19911.8,261.2,1965.0,6326.2,17693.2,110172.4

In [124]:
# Data display coustomization
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', 50)

In [125]:
merged_data

,Country,health,income,inflation,Region,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,Schooling,Status,Birth Rate,GDP,Gross tertiary education enrollment (%),Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Population,Unemployment rate,Urban_population,Clean fuel %,GDP per capita
0,Afghanistan,7.6,1610,9.4,Asia,0.0,65,42,23.3,67,65,0.0,3.6,0,32.5,19101353833.0,9.7,47.9,64.5,638.0,0.3,38041754.0,11.1,9797273.0,35.4,502.1
1,Albania,6.5,9930,4.5,Rest of Europe,4.3,99,98,26.6,99,99,0.0,9.7,0,11.8,15278077447.0,55.0,7.8,78.5,15.0,1.2,2854191.0,12.3,1747593.0,83.7,5352.9
2,Algeria,4.2,12900,16.1,Africa,0.6,95,99,25.5,95,95,0.1,7.9,0,24.3,169988236398.0,51.4,20.1,76.7,112.0,1.7,43053054.0,11.7,31510100.0,99.7,3948.3
3,Angola,2.9,5900,22.4,Africa,6.5,64,64,23.2,62,64,0.9,5.0,0,40.7,94635415870.0,9.3,51.6,60.8,241.0,0.2,31825295.0,6.9,21061025.0,50,2973.6
4,Antigua and Barbuda,6.0,19100,1.4,Central America and Caribbean,9.1,99,84,26.6,86,99,0.2,9.2,0,15.3,1727759259.0,24.8,5.0,76.9,42.0,2.8,97118.0,6.9,23800.0,100,17790.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,Uzbekistan,5.8,4240,16.5,Asia,2.6,99,99,26.7,99,99,0.1,11.4,0,23.3,57921286440.0,10.1,19.1,71.6,29.0,2.4,33580650.0,5.9,16935729.0,82.8,1724.8
142,Vanuatu,5.2,2950,2.6,Oceania,1.4,64,65,26.1,80,64,0.2,6.8,0,29.6,917058851.0,4.7,22.3,70.3,72.0,0.2,299882.0,4.4,76152.0,6.9,3058.1
143,Venezuela,4.9,16500,45.9,South America,6.2,87,83,26.7,87,87,0.4,10.1,0,17.9,482359318768.0,79.3,21.4,72.1,125.0,1.9,28515829.0,8.8,25162368.0,95.5,16915.5
144,Vietnam,6.8,4490,12.1,Asia,3.0,97,65,21.7,97,97,0.1,8.0,0,16.8,261921244843.0,28.5,16.5,75.3,43.0,0.8,96462106.0,2.0,35332140.0,96.1,2715.3
145,Zambia,5.9,3280,14.0,Africa,3.5,90,47,22.5,90,90,4.5,6.9,0,36.2,23064722446.0,4.1,40.4,63.5,213.0,1.2,17861030.0,11.4,7871713.0,10.2,1291.3

In [126]:
merged_data.rename(columns={'Clean fuel %': 'fuel'},inplace=True)
merged_data

,Country,health,income,inflation,Region,Alcohol_consumption,Hepatitis_B,Measles,BMI,Polio,Diphtheria,Incidents_HIV,Schooling,Status,Birth Rate,GDP,Gross tertiary education enrollment (%),Infant mortality,Life expectancy,Maternal mortality ratio,Physicians per thousand,Population,Unemployment rate,Urban_population,fuel,GDP per capita
0,Afghanistan,7.6,1610,9.4,Asia,0.0,65,42,23.3,67,65,0.0,3.6,0,32.5,19101353833.0,9.7,47.9,64.5,638.0,0.3,38041754.0,11.1,9797273.0,35.4,502.1
1,Albania,6.5,9930,4.5,Rest of Europe,4.3,99,98,26.6,99,99,0.0,9.7,0,11.8,15278077447.0,55.0,7.8,78.5,15.0,1.2,2854191.0,12.3,1747593.0,83.7,5352.9
2,Algeria,4.2,12900,16.1,Africa,0.6,95,99,25.5,95,95,0.1,7.9,0,24.3,169988236398.0,51.4,20.1,76.7,112.0,1.7,43053054.0,11.7,31510100.0,99.7,3948.3
3,Angola,2.9,5900,22.4,Africa,6.5,64,64,23.2,62,64,0.9,5.0,0,40.7,94635415870.0,9.3,51.6,60.8,241.0,0.2,31825295.0,6.9,21061025.0,50,2973.6
4,Antigua and Barbuda,6.0,19100,1.4,Central America and Caribbean,9.1,99,84,26.6,86,99,0.2,9.2,0,15.3,1727759259.0,24.8,5.0,76.9,42.0,2.8,97118.0,6.9,23800.0,100,17790.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
141,Uzbekistan,5.8,4240,16.5,Asia,2.6,99,99,26.7,99,99,0.1,11.4,0,23.3,57921286440.0,10.1,19.1,71.6,29.0,2.4,33580650.0,5.9,16935729.0,82.8,1724.8
142,Vanuatu,5.2,2950,2.6,Oceania,1.4,64,65,26.1,80,64,0.2,6.8,0,29.6,917058851.0,4.7,22.3,70.3,72.0,0.2,299882.0,4.4,76152.0,6.9,3058.1
143,Venezuela,4.9,16500,45.9,South America,6.2,87,83,26.7,87,87,0.4,10.1,0,17.9,482359318768.0,79.3,21.4,72.1,125.0,1.9,28515829.0,8.8,25162368.0,95.5,16915.5
144,Vietnam,6.8,4490,12.1,Asia,3.0,97,65,21.7,97,97,0.1,8.0,0,16.8,261921244843.0,28.5,16.5,75.3,43.0,0.8,96462106.0,2.0,35332140.0,96.1,2715.3
145,Zambia,5.9,3280,14.0,Africa,3.5,90,47,22.5,90,90,4.5,6.9,0,36.2,23064722446.0,4.1,40.4,63.5,213.0,1.2,17861030.0,11.4,7871713.0,10.2,1291.3

In [127]:
merged_data.at[22,'fuel']='89.1'
merged_data.at[73,'fuel']='90.2'
merged_data.at[76,'fuel']='25.5'

In [128]:
#convert points column from object to float
merged_data['fuel'] = merged_data['fuel'].astype(float)

In [131]:
from pathlib import Path  
filepath = Path('/Users/cej12/Skrivebord/data/out3.csv')  
filepath.parent.mkdir(parents=True, exist_ok=True)  
merged_data.to_csv(filepath)